### ISSUE TITLE
十分感谢作者！反馈一下四人赛/双人赛遇到的问题。

### ISSUE THREAD

**Issue by oliverking2001** [dundunnp/auto_xuexiqiangguo#10]
十分感谢作者，方便了我们这些每天忙成狗还必须要求学满学分的基层党员。
在官方更新OCR识别后，这个脚本应该是目前唯一能自动比赛的脚本了。

本人手机MI MIX4，5G网络，性能网速应该都不错，强国最新版本，反馈2个问题：
1.答题反应速度较慢。尤其第一题基本在5秒左右作答。如果技术能实现，第一题在1.5-2秒左右，之后0.5-1秒左右是比较合适的。
2.题库准确率较低。目前基本在20%左右。5道题能答对1道就很不错。建议www.syiban.com这个网站的题库比较全，更新也很快，是否有可能抓上面的数据。

再次感谢作者！

**Comment by dundunnp** [comment]
感谢题库，现在我已经突破了做题速度，基本能做到“秒答”，但正确率还是存在缺陷，我会测试你提供的题库的，谢谢

**Comment by dundunnp** [comment]
我已经发布单独测试[四人赛和双人对战脚本](https://hamibot.com/marketplace/sp1Lc)，新版本的四人赛和双人对战答题速度和正确率已经大大提升，欢迎来测试新版本

**Comment by oliverking2001** [comment]
速度非常好！点赞！不过我发现答题时只选择第一个选项，是我哪里设置有问题么。

**Comment by dundunnp** [comment]
又是一直选择第一个吗，你可以多试几次

**Comment by Glaynuo** [comment]
运行报错。 hamibot：错误：type error：cannot call method “child” of null （61a9ce3f16133dca0e955b11.js#27）  啥情况

**Comment by Glaynuo** [comment]
这速度真完美了~~~大佬np！现在就是题库正确率了

**Comment by sancy99** [comment]
错误:TypeError:Cannot call method "child" of null (61a9cfb616133dca0e955b9a.js#27) 
这是什么问题？

**Comment by wuxiwhy** [comment]
> 我已经发布单独测试[四人赛和双人对战剧本](https://hamibot.com/marketplace/sp1Lc)，新版本的四人赛和双人对战答题速度和正确率已经大幅提升，欢迎来测试新版本

点赞

**Comment by dundunnp** [comment]
如果大家还有其他题库可以分享出来，题库越多正确率越高

**Comment by dundunnp** [comment]
> 错误:TypeError:Cannot call method "child" of null (61a9cfb616133dca0e955b9a.js#27) 这是什么问题？

注意看脚本说明

**Comment by oliverking2001** [comment]
> 又是一直选择第一个吗，你可以多试几次

又测试了几次，绝大多数时候都可以识别出题目，速度很给力。
另提醒作者注意保护自己避免留痕，防范有关部门介入引起不必要的麻烦！
十分感谢作者！

**Comment by oliverking2001** [comment]
> 错误:TypeError:Cannot call method "child" of null (61a9cfb616133dca0e955b9a.js#27) 这是什么问题？

点击运行后手动切换到积分列表

**Comment by sancy99** [comment]
> 

OK，准确率80%有了

**Comment by x0829** [comment]
漂亮，虽然还是输了，答错题库会自动更新吗，会的话我刷一会题库

**Comment by dundunnp** [comment]
> 漂亮，虽然还是输了，答错题库会自动更新吗，会的话我刷一会题库

哈哈哈哈哈，不会的，题库是利用其他网站，毕竟刷题库这事不像是正常人干的

**Comment by x0829** [comment]
有个小问题，我这边使用的时候只答一次四人赛，都是这样吗？

**Comment by dundunnp** [comment]
> 有个小问题，我这边使用的时候只答一次四人赛，都是这样吗？

是的，这个只是单独拿出来测试用的

**Comment by DerekWeih** [comment]
> > 有个小问题，我这边使用的时候只答一次四人赛，都是这样吗？
> 
> 是的，这个只是单独拿出来测试用的

四人对战版没法选延时了，也不知道有没有正确的OCR出来，测试了三十多次，基本上97%都是选择第一项。

**Comment by x0829** [comment]
1.2版本我俩个号都有个毛病，进入答题界面后没反应，切换一下才开始答题
