### ISSUE TITLE
新版脚本运行至四人赛时报错

### ISSUE THREAD

**Issue by matrixnobody** [dundunnp/auto_xuexiqiangguo#215]
![IMG_20220322_092516](https://user-images.githubusercontent.com/51011082/159389404-5376672e-dbdd-4953-86df-b7927630ab6f.jpg)

**Comment by luoyuu77** [comment]
我也是

**Comment by qq158668** [comment]
我也是

**Comment by dundunnp** [comment]
用的是啥版本的学习qg

**Comment by matrixnobody** [comment]
> 用的是啥版本的学习qg

2.33.0 
早上更新了[McMug2020](https://github.com/McMug2020) 14.1 版本又不出现该错误了

**Comment by McMug2020** [comment]
没动过这部分模块，我只改了On亮屏、全程静音和发表言论的文字

**Comment by matrixnobody** [comment]
> 没动过这部分模块，我只改了On亮屏、全程静音和发表言论的文字

下个版本能把 关闭电台 这个代码注释掉么？总是到这个地方脚本莫名停止，也无日志可查

**Comment by McMug2020** [comment]
> > 没动过这部分模块，我只改了On亮屏、全程静音和发表言论的文字
> 
> 下个版本能把 关闭电台 这个代码注释掉么？总是到这个地方脚本莫名停止，也无日志可查

实测没有问题啊，打开hamibot需要的权限如后台启动，或者有条件的话，建议在PC端用浏览器扩展刷
