### ISSUE TITLE
请问遇到答案换顺序了能解决吗

### ISSUE THREAD

**Issue by linkfoxcn** [dundunnp/auto_xuexiqiangguo#223]
四人对战我已经错了不少了，题库网站本身的答案是旧的，是不是这个影响了，麻烦看一看，谢谢。

**Comment by dundunnp** [comment]
能解决，所以这就是为什么现在答题速度慢了，因为要ocr每个选项

**Comment by linkfoxcn** [comment]
如果更新了ocr每个选项，能不能把单独四人双人的再更新一下，谢谢
