### ISSUE TITLE
大侠，关于四人赛和双人对战的截屏边距

### ISSUE THREAD

**Issue by 85524365** [dundunnp/auto_xuexiqiangguo#232]
大侠，一直用你滴软件，感谢了。
记得以前教程里有个关于关于四人赛和双人对战的截屏边距设置，当初没认真学习，现在想研究一下，能传上来学习学习吗？谢谢

**Comment by dundunnp** [comment]
不建议学习那个版本的了，还是比较不友好的，不过你真想要的话也是有的https://github.com/dundunnp/hamibot-auto_xuexiqiangguo/tree/version-5

**Comment by 85524365** [comment]
感谢大神百忙中回复，我是想研究一下截屏的方法，就是以前教程里有个 距离边距 0.4cm，上下左右等等的

**Comment by 85524365** [comment]
应该是一张图片
