### ISSUE TITLE
Auto.js版希望增加本地第三方OCR

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/auto_xuexiqiangguo#252]
全部用百度OCR的话，多账号 免费次数耗不起啊，建议能增加本地第三方OCR，具体方法可以参考GitHub上Study的开源脚本Study_hamibot 谢谢

**Comment by zhufscug** [comment]
我算了下，一个月大概要多不到100次OCR，还不到一块钱，我觉得耗得起

**Comment by zhufscug** [comment]
计算如下，35*31=1085，减去免费资源1000，还剩85，目前价格是一分钱一次，一个月不超过一块钱

**Comment by McMug2020** [comment]
额，第二个账号就10块钱了…
https://github.com/Twelve-blog/Study_hamibot
Study的本地OCR已经很成熟了，应该可以直接拿来主义

**Comment by wjhey** [comment]
//本地OCR，随便改一下将就用了
function ocr_ocrImage(img) {
	console.info("**本地ocr***");
    var right_flag = false;
    var answer_left = "";
    var answer_right = "";
    var answer = "";
    let ocr = $plugins.load("com.hraps.ocr");
let bitmap = img.getBitmap();
results = ocr.detect(bitmap, 1);
var html ="";
for (var i = 0; i < results.size(); i++) {
  var re = results.get(i);
    html += results.get(i).text;

 }
    log("OCR结果"+html);
	var answer=html;
    //answer = answer_right.length > answer_left.length ? answer_right : answer_left;
    answer = answer.replace(/\s*/g, "");
    answer = answer.replace(/,/g, "，");
    answer = answer.slice(answer.indexOf('.') + 1);
    answer = answer.slice(0, 20);
	 //log("answer"+answer);
    return answer;
}
