### ISSUE TITLE
完了停更了  以后怎么办

### ISSUE THREAD

**Issue by sss521** [dundunnp/auto_xuexiqiangguo#253]
![image](https://user-images.githubusercontent.com/50821901/160642835-3d274df2-4086-4646-9504-97254e7abaea.png)

**Comment by 11mina** [comment]
你搞错脚本的作者了

**Comment by sss521** [comment]
![image](https://user-images.githubusercontent.com/50821901/160656597-d5a6bb7b-04b1-4c76-93c7-34518953b279.png)
发生了什么 不要吓我

**Comment by anby1** [comment]
作者名字和项目全搞错还能找到这社区发就离谱

**Comment by McMug2020** [comment]
问题不大，Study作者的hamibot脚本被人抓包盗用，被迫开源然后停更了。
聚散终有时，再见亦无期。

**Comment by whhxmwhh** [comment]
这个是使用最稳定的脚本。可惜，能用就好。
