### ISSUE TITLE
14.5版本代码的一些问题

### ISSUE THREAD

**Issue by Lihewin** [dundunnp/auto_xuexiqiangguo#277]
# 14.5版本代码的一些问题
## Bug1：关闭广播
    问题复现机型：Honor 5x、Redmi K20 Pro

近期由于未知原因，我的手机发生了几次关闭广播时在模拟点击v_playing按钮之前广播就已经自动停止播放的情况，导致模拟点击v_playing的waitFor函数一直阻塞。以下是对代码的修改建议。
```javascript
//Hamibot版本396行
className('android.widget.ImageView').clickable(true).id('v_playing').waitFor();
className('android.widget.ImageView').clickable(true).id('v_playing').findOne().click();
```
修改为
```javascript
if (!textStartsWith('最近收听').exists()) {
    className('android.widget.ImageView').clickable(true).id('v_playing').waitFor();
    className('android.widget.ImageView').clickable(true).id('v_playing').findOne().click();
}
```
## Bug2：百灵竖屏视频大于一分钟跳过时的问题
    问题复现机型：Honor 5x（长宽比16：9）

这个问题在长宽比较低的机型上容易复现。跳过采用了`refresh(orientation)`函数以模拟手指滑动，而在部分机器上这个滑动的起始点正好在视频进度条2/3的地方，可以实验，当向上拖动进度条时，并不会切换至下一个视频，而是将视频进度跳转到触摸点。从而导致了在这些机器上大于一分钟的视频会不断在同一个时间点上刷新的诡异现象。以下是对代码的修改建议。
```javascript
//Hamibot版本437行
if (Number(current_video_time.slice(0, 3)) >= 1) {
    refresh(true);
    sleep(random_time(delay_time));
    continue;
}
```
修改为
```javascript
if (Number(current_video_time.slice(0, 3)) >= 1) {
    // 在屏幕2/3处开始滑动，这样应该兼容大多数机器了
    swipe(device.width / 2, (device.height * 2) / 3, device.width / 2, (device.height * 2) / 15, random_time(delay_time / 2));
    sleep(random_time(delay_time));
    continue;
}
```

## Bug3：以像素为参数的脚本在极端条件下运行的问题
    问题复现机型：Honor 5x（长宽比16：9）

这个问题在大多数机器上不会复现，除非机器的分辨率特别之低。我的Honor 5x为了保证性能，屏幕分辨率被调到了360x640，导致以像素为参数的脚本无法执行。虽然并不太重要，但还是希望代码能进行更改。以下是对代码的修改建议。
```javascript
//Hamibot版本693、877、1009、1066行，也许还有其他位置
swipe(500, 1700, 500, 500, random_time(delay_time / 2));
```
修改为
```javascript
refresh(true);
```

## Bug4：低清设备的截图二值化问题
    问题复现机型：Honor 5x（长宽比16：9）

机器条件同Bug3，表现为在截图并二值化时部分机器由于色差等问题无法进行正常的二值化。建议放宽颜色区域。
```javascript
//Hamibot版本918行
var img = images.inRange(captureScreen(), '#800000', '#FF0000');
```
修改为
```javascript
//这个值我在不同机器上调试过，识别效果比较可以
var img = images.inRange(captureScreen(), '#600000', '#FF6565');
```

## Bug5：订阅时出现的一些问题
    问题复现机型：Redmi K20 Pro，xxqg版本2.33.0

这个问题在手机上出现过数次，现象为在下拉到底部后抛出异常。这个问题我还未能复现，待更新。

## Bug5更新：
已经复现问题。问题为：当某个板块订阅量较少时，在订阅模块中成功点击两次红色订阅按钮后，仍进行了一次`swipe()`操作，导致在其后的已订阅控件对比中，最后一个已订阅控件被拉出屏幕边界，导致`complete_subscribe_pos2`为`null`，脚本便抛出异常`Cannot read property x from null`。以下是对代码的修改建议。
```javascript
...
//Hamibot版本1312行
while (subscribe_pos && num_subscribe < 2);
// 通过对比 检测到的已订阅控件 的位置来判断是否滑到底部
...
```
修改为
```javascript
...
//Hamibot版本1312行
while (subscribe_pos && num_subscribe < 2);
if (num_subscribe >= 2) break;
// 通过对比 检测到的已订阅控件 的位置来判断是否滑到底部
...
```
只需要在成功订阅两次后退出即可。

**Comment by dundunnp** [comment]
哇！我认为所有提出issue的人都应该向你学习！标准的格式、完整的信息！
Bug1是我也经常会出现的，但我看没什么人提出过这个问题，我也就懒得解决了。。感谢你！
Bug2-5我是真没想到这么细致全面，你真是个细心的人！

不过我强烈建议你pr你所修改的代码，我直接复制你发出修改的代码我会感到愧疚的hhhh
看的出来你花很多时间看了我写的乱七八糟的代码，你不成为代码的贡献者是我的遗憾

**Comment by Lihewin** [comment]
谢谢夸奖！我会尝试PR代码。
