### ISSUE TITLE
请求横屏截图权限无法点击允许确认

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/auto_xuexiqiangguo#283]
鸿蒙2.0 强国2.33.0 hamibot1.31 经测试请求横屏截图权限允许按钮无法点击，代码与原来的不一样

v15.0
//请求横屏截图权限
cap_t = threads.start(function () {
    try {
        var beginBtn;
        if ((beginBtn = classNameContains("Button").textContains("开始").findOne(delay_time)));
        else beginBtn = classNameContains("Button").textContains("允许").findOne(delay_time);
        beginBtn.click();
    } catch (error) { }
});

v14.4
//请求横屏截图权限
threads.start(function () {
    try {
        var beginBtn;
        if (beginBtn = classNameContains("Button").textContains("开始").findOne(delay_time));
        else (beginBtn = classNameContains("Button").textContains("允许").findOne(delay_time));
        beginBtn.click();
    } catch (error) {
    }
});

**Comment by dundunnp** [comment]
问题已经解决了，是因为delay_time还没初始化
