### ISSUE TITLE
没订阅满时卡死在订阅模块无限循环

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/auto_xuexiqiangguo#288]
鸿蒙2.0 强国2.33.0 hamibot1.31

**Comment by Lihewin** [comment]
这是一个尝试用来解决若有重复订阅不得分的特性，当没有拿满两分时重复操作一直到拿满。
如果发生重复进入订阅功能而不进行订阅操作的问题，请更加详细地描述。

**Comment by McMug2020** [comment]
> 这是一个尝试用来解决若有重复订阅不得分的特性，当没有拿满两分时重复操作一直到拿满。 如果发生重复进入订阅功能而不进行订阅操作的问题，请更加详细地描述。

当天只有一个订阅，已完成。退出订阅后又去检查得分，然后又进到订阅，继续点击，然后又退出，检查得分后又进入，我已经关闭订阅模块了。烦请检查下代码是否有误，谢谢
