### ISSUE TITLE
自动进入四人赛或双人或每周答题以及各类答题后，开始答题就报错

### ISSUE THREAD

**Issue by l666l** [dundunnp/auto_xuexiqiangguo#325]
![QQ图片20220504111625](https://user-images.githubusercontent.com/72931399/166618869-aadc4be4-91c1-49c3-87cf-fcd9abae5168.jpg)

**Comment by Narut0123** [comment]
pixel 4 XL 手机，使用hamibot v1.3.1，同样出现此状况

**Comment by syncake** [comment]
也碰到过，之前是华为，后来生气专门买了个pixel3，换原生系统就过了

**Comment by lovewanghui** [comment]
> 也碰到过，之前是华为，后来生气专门买了个pixel3，换原生系统就过了

你只是更换了手机, 就解决了吗? 我也遇到了, 这个问题, 我看这个报错信息信息是说方法没有实现. 搞不懂了. 这个跟系统环境有关系吗?

**Comment by lovewanghui** [comment]
> pixel 4 XL 手机，使用hamibot v1.3.1，同样出现此状况

现在问题, 解决掉了吗? 可以分享一下吗?
