### ISSUE TITLE
今天双人赛前遇到验证了，你们遇到了吗

### ISSUE THREAD

**Issue by alikankan** [dundunnp/auto_xuexiqiangguo#340]
验证是滑动块从左边滑动到最右边，提示超时不滑动学习就不会得分，忘记截图了，大家远程挂注意下！

**Comment by Mackiewu** [comment]
我也遇到了，发现晚了，双人赛输了

**Comment by qingshangithub** [comment]
遇到了+1

**Comment by zhuzaitianya** [comment]
同样遇到，在双人赛比赛到中间位置出现滑块验证。

**Comment by lazybabyz** [comment]
同样遇到

**Comment by alikankan** [comment]
![Screenshot_20220517_193137_com ss android article news](https://user-images.githubusercontent.com/77603199/168801355-2829ab74-c149-49df-b6c2-25a9f5ae312b.png)
图片就这样，一般出现四人赛，我是双人赛

**Comment by 2100310773** [comment]
同样

**Comment by babi-Q** [comment]
今天四人赛第二场出现了

**Comment by toutwoa** [comment]
双人对战的时候遇到了！

**Comment by zhufscug** [comment]
我也遇到了，有哪位大佬知道是怎么被检测到的嘛

**Comment by dundunnp** [comment]
> 我也遇到了，有哪位大佬知道是怎么被检测到的嘛

我换了一个新号试了试，我用手动答也会出现这个滑动验证，貌似是因为答题速度太快导致的

**Comment by alikankan** [comment]
> > 我也遇到了，有哪位大佬知道是怎么被检测到的嘛
> 
> 我换了一个新号试了试，我用手动答也会出现这个滑动验证，貌似是因为答题速度太快导致的

感觉是多设备登录的，答题速度有点快的都可能弹出验证，能加个线程检测到就滑动吗

**Comment by dundunnp** [comment]
我已经解决了滑动验证的问题，现在脚本可以自动处理滑动验证了，请更新最新版本的代码

**Comment by toutwoa** [comment]
> 我已经解决了滑动验证的问题，现在脚本可以自动处理滑动验证了，请更新最新版本的代码

优秀！

**Comment by alikankan** [comment]
dundun已更新处理异常代码
