### ISSUE TITLE
四人赛双人对战答错版+滑动验证后问题

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/auto_xuexiqiangguo#348]
我改了下AUTO那个答错的脚本，不管啥账号只要运行就会有验证，难道是触发了啥？
答错脚本是答的很慢的那种，但在第一二轮就会触发验证，不清楚平台的验证机制是啥，大家可以下载测试下

https://github.com/McMug2020/hamibot-auto_xuexiqiangguo/blob/main/四人赛双人对战答错版/

Hamibot脚本 https://hamibot.com/marketplace/vOvru?invite=vYRjBCHYZdU6gQtvdnrtTd5E

**Comment by zhufscug** [comment]
> 我改了下AUTO那个答错的脚本，不管啥账号只要运行就会有验证，难道是触发了啥？ 答错脚本是答的很慢的那种，但在第一二轮就会触发验证，不清楚平台的验证机制是啥，大家可以下载测试下
> 
> [https://github.com/McMug2020/hamibot-auto_xuexiqiangguo/blob/main/四人赛双人对战答错版/](https://github.com/McMug2020/hamibot-auto_xuexiqiangguo/blob/main/%E5%9B%9B%E4%BA%BA%E8%B5%9B%E5%8F%8C%E4%BA%BA%E5%AF%B9%E6%88%98%E7%AD%94%E9%94%99%E7%89%88/)
> 
> Hamibot脚本 https://hamibot.com/marketplace/vOvru?invite=vYRjBCHYZdU6gQtvdnrtTd5E

同设备多账号登录哈哈哈

**Comment by McMug2020** [comment]
这个滑动验证和淘宝一模一样，可能是阿里直接拿过来用的技术，操作太频繁，切换页面动作太快，都会让平台感知到像是非人的操作。
