### ISSUE TITLE
autoxjs有开源的本地ocr

### ISSUE THREAD

**Issue by hzfinternet** [dundunnp/auto_xuexiqiangguo#349]
很好奇大家都没了解autoxjs吗，就是相当于autojs的加强版，autojs pro的免费开源版，功能比不上autojs pro但是比autojs强了不少。
autoxjs有本地ocr功能，识别速度挺快的，希望up主能用上，链接：
https://github.com/kkevsekk1/AutoX/releases

**Comment by hzfinternet** [comment]
//附上我测试用的代码看看能不能减少up主的工作量
auto.waitFor();//等待获取无障碍辅助权限
threads.start(function () {
    try {
        var beginBtn;
        if (beginBtn = classNameContains("Button").textContains("开始").findOne(1000));
        else (beginBtn = classNameContains("Button").textContains("允许").findOne(1000));
        beginBtn.click();
    } catch (error) {
    }
})
requestScreenCapture();
console.show();
log("倒计时5秒开始");
for(var i = 5; i>0 ; i--){
    log(i);sleep(1000);}
    
let img = captureScreen(); log("截图");
//var res = JSON.stringify(paddle.ocrText(img, 8, false));
var res = JSON.stringify(paddle.ocrText(img));
img.recycle();
log("ocr识别结果："+res);

res = res.replace(/","/g,"");log("去掉引号后内容：" + res);//去掉所有的","字符串，/g表示所有
var i = res.indexOf(".");log(".的位置："+i+1);//找.在文本中位置，结果是第length-1个字符
res = res.slice(i+1);//这里即删除.以前的字符串，就剩下题目和答案
var n = res.indexOf("出题");log("出题 的位置：" + n);
if (n>4) {res = res.substring(0, n);};log("处理头尾后的文本：" + res)//只保留substring(from, to)
var question = res.substring(0, res.indexOf("A.")); log("题目：" + question);
res = res.slice(question.length+2);log("全选项：" + res);//去除题目和A.
var resSplit = res.split(/"A\.|B\.|C\.|D\.|E\."/);//不知道为啥A.去不掉，所以在上一句删多2个
//resSplit[0] = resSplit[0].slice(2);//没有A.不用做这步
resSplit[resSplit.length-1] = resSplit[resSplit.length-1].slice(0, -2);
for (let arr = 0; arr < (resSplit.length); arr++) {
    log("选项"+ (arr+1) + "："  + resSplit[arr]);
}

**Comment by hzfinternet** [comment]
//附上我测试用的代码看看能不能减少up主的工作量
auto.waitFor();//等待获取无障碍辅助权限
threads.start(function () {
    try {
        var beginBtn;
        if (beginBtn = classNameContains("Button").textContains("开始").findOne(1000));
        else (beginBtn = classNameContains("Button").textContains("允许").findOne(1000));
        beginBtn.click();
    } catch (error) {
    }
})
requestScreenCapture();
console.show();
log("倒计时5秒开始");
for(var i = 5; i>0 ; i--){
    log(i);sleep(1000);}
    
let img = captureScreen(); log("截图");
//var res = JSON.stringify(paddle.ocrText(img, 8, false));
var res = JSON.stringify(paddle.ocrText(img));
img.recycle();
log("ocr识别结果："+res);

res = res.replace(/","/g,"");log("去掉引号后内容：" + res);//去掉所有的","字符串，/g表示所有
var i = res.indexOf(".");log(".的位置："+i+1);//找.在文本中位置，结果是第length-1个字符
res = res.slice(i+1);//这里即删除.以前的字符串，就剩下题目和答案
var n = res.indexOf("出题");log("出题 的位置：" + n);
if (n>4) {res = res.substring(0, n);};log("处理头尾后的文本：" + res)//只保留substring(from, to)
var question = res.substring(0, res.indexOf("A.")); log("题目：" + question);
res = res.slice(question.length+2);log("全选项：" + res);//去除题目和A.
var resSplit = res.split(/"A\.|B\.|C\.|D\.|E\."/);//不知道为啥A.去不掉，所以在上一句删多2个
//resSplit[0] = resSplit[0].slice(2);//没有A.不用做这步
resSplit[resSplit.length-1] = resSplit[resSplit.length-1].slice(0, -2);
for (let arr = 0; arr < (resSplit.length); arr++) {
    log("选项"+ (arr+1) + "："  + resSplit[arr]);
}

**Comment by kobe01116** [comment]
> 很好奇大家都没了解autoxjs吗，就是相当于autojs的加强版，autojs pro的免费开源版，功能比不上autojs pro但是比autojs强了不少。 autoxjs有本地ocr功能，识别速度挺快的，希望up主能用上，链接： https://github.com/kkevsekk1/AutoX/releases

你好  能交流吗? 我QQ : 1372113810
