### ISSUE TITLE
四人双人：11：16:53.017/D:四人赛 11:16:54.223/E:ReferenceError:"back track" is not defined.(6264c6****429.js#553) ReferenceError:"back track"is not defined. at 6264c6****429.js:553：0

### ISSUE THREAD

**Issue by Watson0635** [dundunnp/auto_xuexiqiangguo#356]
11：16:53.017/D:四人赛
11:16:54.223/E:ReferenceError:"back track" is not defined.(6264c6*****429.js#553)
ReferenceError:"back track"is not defined.
at 6264c6*****429.js:553：0

**Comment by dundunnp** [comment]
代码是否复制完整呢，代码中不包含“back track”啊
