### ISSUE TITLE
各模块的已完成情况获取错误

### ISSUE THREAD

**Issue by raawaa** [dundunnp/auto_xuexiqiangguo#357]
qg版本：2.33
运行方式：hamibot

从 2022-05-20 开始获取到的各模块的完成情况就不对了。

调试发现，取到的`finish_list`内容，和实际完成情况有错位，推测是页面改版导致UI元素序号不对了。可能需要如下相关代码中的`i`的起始值。

https://github.com/dundunnp/auto_xuexiqiangguo/blob/b83f7a62fd765a155a021ce2de029f48a1b23f27/Hamibot/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js#L307-L333

**Comment by dundunnp** [comment]
是的，应该是网页改版导致的，感谢

**Comment by raawaa** [comment]
> 为啥我刚刚测试貌似一切都正常啊，是不是改回来了？或者你的强国版本自动更新了

例如「我要选读文章」的完成状态，实际获取的是「视频学习时长」的状态。有错位。

光看表象的话可能察觉不出来，比如全都未完成的话，就感觉不到区别。

**Comment by raawaa** [comment]
本来我以为是炝锅版本的问题，但是降级到2.33还是有这个问题。

**Comment by raawaa** [comment]
难道是我安卓的问题？
我前两天正好从安卓11升级到了安卓12（LineageOS 19.1）。

好像就是从此之后出了问题。

**Comment by raawaa** [comment]
目前遇到的问题基本都是同一个原因：原本 hamibot 识别成 `android.view.View` 的 UI 组件现在被识别成了 `android.widget.TextView` 或许就是因为 hamibot 在 android 12 上跑有问题……

**Comment by dundunnp** [comment]
我觉得可能是android系统的问题吧，我的组件还是android.view.View，不过到是可以多创个android12版的代码，感谢

**Comment by dundunnp** [comment]
那android12版的代码就靠你了（狗头），我也没android12的手机
