### ISSUE TITLE
Depth不同型号的机子不一样

### ISSUE THREAD

**Issue by pkusocold** [dundunnp/auto_xuexiqiangguo#365]
手机mate 30，系统鸿蒙2.0.0.216，学xi用的是作者提供的2.33版，其中depth和作者提供的很不一样，比如“学习积分”，在我这里depth是8,作者用的是21，四人答题我这里depth是15，作者用的是21。运行不起来的可以自己手动改一下。

**Comment by raawaa** [comment]
这差得也太多了吧。鸿蒙的安卓血统是不是已经变得「非我族类」了

**Comment by pkusocold** [comment]
> 

就是有点不正常 难怪很多脚本在其它地方正常运行 在我机子上怎么都跑不起来 改一下就好了
