### ISSUE TITLE
大家现在答题对战正确率高吗？

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/auto_xuexiqiangguo#385]
本人手机，鸿蒙2.0 强国2.33.0 hamibot1.31
测试运行四人赛双人对战模块时而正常果决，时而抽风躺平，但通常情况下很难拿高分，不晓得是不是设备的问题，作者提到最优哈希值6469，难道答题正确率和这个神秘代码有关，可能每台设备得到的值不一样？ 按照隔壁脚本来说1.3.1自带OCR应该够用了，且hamibot改用最新版也不行

**Comment by alikankan** [comment]
我这几天把处理异常的代码嫁接过去，比赛全胜，我又把延迟时间从1增加了10倍，避免太厉害了

**Comment by photism** [comment]
小米miui13，对战包括答题一直都很顺利，该对的时候全对，该错的时候全错，非常偶尔的时候会抽风，手机重启一下基本也就好了

**Comment by shadow1974** [comment]
最好增加一个自定义答题速度功能，要不答太快太准了

**Comment by ddkk3000** [comment]
> 最好增加一个自定义答题速度功能，要不答太快太准了

不会吧。错误的几率很高啊

**Comment by ddkk3000** [comment]
> 我这几天把处理异常的代码嫁接过去，比赛全胜，我又把延迟时间从 1 增加了 10 倍，避免太厉害了

请问怎么做。

**Comment by McMug2020** [comment]
我怀疑你们用的都是高端旗舰
