### ISSUE TITLE
答题增加定时更新题库功能，题库保持更新很重要

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/auto_xuexiqiangguo#408]
作者好像没提供自动检测更新题库的功能，腾讯云的题库也好久没更新了，增加如下代码可以定时更新GitHub上的在线题库（XXQG_TiKu）

var date = new Date();
// 每周五定时更新题库，周日为0
var update_day = date.getDay();
if (update_day == 5) storage.remove('answer_question_map1');
// 或设定每月某日定时更新
// var update_day = date.getDate();
// if (update_day == 3) storage.remove('answer_question_map1');

**Comment by fmou** [comment]
感谢大大们无私奉献
