### ISSUE TITLE
有懂数据库的大佬吗？能否把这个答题题库.db文件转成.json

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/auto_xuexiqiangguo#409]
当前脚本采用的是**挑战答题**（XXQG_TiKu）的题库，与四人赛双人对战不完全一致，本地和在线没找到答案有时会连续错
**题库.db地址** https://github.com/McMug2020/XXQG_TiKu/blob/main/%E9%A2%98%E5%BA%93.db
链接是从某氪金软件导出的，能用SQLiteStudio正常打开，看有没有大佬能转化成现在正在用的这种格式，正确答案是字母显示的与选项顺序对应，格式稍微不同
目前用的本地题库地址https://github.com/mondayfirst/XXQG_TiKu/blob/main/%E9%A2%98%E5%BA%93_%E6%8E%92%E5%BA%8F%E7%89%88.json

**Comment by McMug2020** [comment]
![mmexport1654271334022](https://user-images.githubusercontent.com/92876629/171900691-3984ba18-297b-4f73-9316-0d455c708824.png)

**Comment by twinklelucas** [comment]
这个题库有比XXQG_Tiku全吗？

**Comment by McMug2020** [comment]
> 这个题库有比XXQG_Tiku全吗？

这是一个一直在更新的大题库，包括挑战答题四人赛双人对战的题目

**Comment by McMug2020** [comment]
我又看了一下好像用不到数据库知识，会Excel办公软件就行，不用麻烦看官了

**Comment by McMug2020** [comment]
已更新上传
https://git.yumenaka.net/https://raw.githubusercontent.com/McMug2020/XXQG_TiKu/main/%E9%A2%98%E5%BA%93_McMug2020.json
