### ISSUE TITLE
更新挑战答题四人赛双人对战大题库（已手动清洗，推荐替换）

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/auto_xuexiqiangguo#411]
当前脚本采用的是挑战答题（XXQG_TiKu）的题库，与四人赛双人对战不完全一致，找了个最新的氪金软件题库手动转化了下，可以到如下地址下载试试看
https://raw.githubusercontent.com/McMug2020/XXQG_TiKu/main/%E9%A2%98%E5%BA%93_McMug2020.json

脚本修改方法见https://github.com/McMug2020/hamibot-auto_xuexiqiangguo/commit/b8bb2086fa5d6ccd65d6b44efe8ea20f7038bbee

**Comment by fmou** [comment]
四人赛出现如下错误代码
![IMG_8870](https://user-images.githubusercontent.com/104907189/171993595-dfcf848f-c6be-43d1-ac6f-9af65df88958.JPG)

**Comment by McMug2020** [comment]
测试过没有问题啊
四人赛双人对战独立脚本
https://hamibot.com/marketplace/wP0FS?invite=9kQ5VBbqLFWhCMCptbG9B55K

**Comment by fmou** [comment]
是这个版本，我也不知道什么原因，估计是老旧手机的问题吧。

**Comment by McMug2020** [comment]
> 是这个版本，我也不知道什么原因，估计是老旧手机的问题吧。

强国必须是2.33.0，系统UI11.0以下

**Comment by McMug2020** [comment]
已手动清洗，推荐替换试试

**Comment by fmou** [comment]
感谢大大

**Comment by Witcherchow** [comment]
> 

包括UI 11.0吗 ?

**Comment by Edward88888888** [comment]
替换这个能提高正确率吗？有详细教程吗？谢谢大神。。

**Comment by McMug2020** [comment]
> > 
> 
> 包括UI 11.0吗 ?

包括的

**Comment by McMug2020** [comment]
> 替换这个能提高正确率吗？有详细教程吗？谢谢大神。。

不能，目前用百度OCR正确率已经很高了，题库只是增加了确定性；方法前面已经写了。

**Comment by fmou** [comment]
@McMug2020 四人赛百度OCR识别乱码太多，然后全选A。使用本地OCR就不会乱码，但是选择的时候还是全选A（Auto PK
v7.5）
![0](https://user-images.githubusercontent.com/104907189/172574994-480036ac-a5e8-4ba8-a2e4-8655d484ba6f.jpg)

**Comment by McMug2020** [comment]
![Screenshot_20220608_203430](https://user-images.githubusercontent.com/92876629/172617609-2a85eb36-4fa0-46d0-a051-195f922ee657.jpg)
刚测试了一下没问题。正常的日志是这样的，用百度OCR完全识别，大比分获胜

**Comment by Edward88888888** [comment]
> > @McMug2020 四人赛百度OCR识别乱码太多，然后全选A。使用本地OCR就不会乱码，但是选择的时候还是全选A（Auto PK v7.5） ![0](https://user-images.githubusercontent.com/104907189/172574994-480036ac-a5e8-4ba8-a2e4-8655d484ba6f.jpg)
> 
> 你这个每次题目/选项OCR后面都有：44，明显不太正常，最好能重启一下设备再试试

好像脚本出现问题了。昨天还正常，今天打不开脚本。是否qg官方更新了什么东西。。点运行后一点反应没有

**Comment by fmou** [comment]
我跟楼上一样，点运行没有任何反应，好像点击不了，本来点击后有个“转圈”，现在没有。
![微信截图_20220609005026](https://user-images.githubusercontent.com/104907189/172673336-bb0f17c3-13c2-4e11-bd1a-731da00a66dd.png)

**Comment by Edward88888888** [comment]
> 我跟楼上一样，点运行没有任何反应，好像点击不了，本来点击后有个“转圈”，现在没有。 ![微信截图_20220609005026](https://user-images.githubusercontent.com/104907189/172673336-bb0f17c3-13c2-4e11-bd1a-731da00a66dd.png)

问题已经解决。不知道具体原因，但是把脚本删除后重新安装并设置就没问题了。

**Comment by McMug2020** [comment]
据了解应该是hamibot平台昨天自身的问题
