### ISSUE TITLE
四人赛双人对战Mod版（自建题库，评估后更新最优hash值）

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/auto_xuexiqiangguo#460]
改完后目前用起来还可以，大家可以安装体验下，自用脚本供参考
https://hamibot.com/marketplace/wP0FS?invite=9kQ5VBbqLFWhCMCptbG9B55K

代码地址：https://github.com/McMug2020/hamibot-auto_xuexiqiangguo/tree/main/%E5%9B%9B%E4%BA%BA%E8%B5%9B%E5%8F%8C%E4%BA%BA%E5%AF%B9%E6%88%98
（评估后更新最优hash值为8539）

**Comment by li1472** [comment]
四人对战报错了

**Comment by McMug2020** [comment]
> 四人对战报错了

刚测试了一下，没有问题

**Comment by li1472** [comment]
你用的强国是哪个版本呢

**Comment by McMug2020** [comment]
> 你用的强国是哪个版本呢

2.33.0 脚本安装页面上有写

**Comment by pioneerxft** [comment]
楼主你好，感谢你的自用脚本分享，在这个界面安装一周以来使用很时流畅舒服。在使用过程中有个问题：总的来说就是分享在HAMIBOT的3个脚本运行完毕之后都不会自动返回主页，软件会24小时在线，备用机有时候会有卡顿，后面的脚本运行过程中偶有报错。希望加个脚本运行结束后自动返回桌面的功能。

**Comment by McMug2020** [comment]
> 楼主你好，感谢你的自用脚本分享，在这个界面安装一周以来使用很时流畅舒服。在使用过程中有个问题：总的来说就是分享在HAMIBOT的3个脚本运行完毕之后都不会自动返回主页，软件会24小时在线，备用机有时候会有卡顿，后面的脚本运行过程中偶有报错。希望加个脚本运行结束后自动返回桌面的功能。

我已经提供代码了你可以直接复制脚本运行

**Comment by McMug2020** [comment]
题库存取最优hash值评估代码
https://github.com/McMug2020/hamibot-auto_xuexiqiangguo/blob/main/%E6%89%BE%E5%87%BA%E6%9C%80%E4%BC%98hash%E5%80%BC.js

**Comment by pioneerxft** [comment]
> > 楼主你好，感谢你的自用脚本分享，在这个界面安装一周以来使用很时流畅舒服。在使用过程中有个问题：总的来说就是分享在HAMIBOT的3个脚本运行完毕之后都不会自动返回主页，软件会24小时在线，备用机有时候会有卡顿，后面的脚本运行过程中偶有报错。希望加个脚本运行结束后自动返回桌面的功能。
> 
> 我已经提供代码了你可以直接复制脚本运行

多谢楼主，好人一生平安
