### ISSUE TITLE
滑块验证无法通过

### ISSUE THREAD

**Issue by GZR-zhuanjia** [dundunnp/auto_xuexiqiangguo#461]
更新后滑块验证数量增加，但识别ai更新，之前的代码无法通过

**Comment by McMug2020** [comment]
0f5f0e58e790dec41bfd5ce128cd04b0d9d22dff

**Comment by McMug2020** [comment]
漏了，注意最后一行要加exit();结束脚本

**Comment by onesixsix** [comment]
> 漏脚本了，注意最后一行要加exit();结束

感谢分享，用了你的能过验证了，自己改了一下在autojs上用的，只改了前面配置那，别的都没动

**Comment by McMug2020** [comment]
> > 漏脚本了，注意最后一行要加exit();结束
> 
> 感谢分享，用了你的能过验证了，自己改了一下在autojs上用的，只改了前面配置那，别的都没动

实现方式不一样了，建议按着上面的方法改啊

**Comment by dundunnp** [comment]
> [0f5f0e5](https://github.com/dundunnp/auto_xuexiqiangguo/commit/0f5f0e58e790dec41bfd5ce128cd04b0d9d22dff)

我引用了你的滑动验证模块的代码，刚开始很好，但后面几天发现还是通过不了，软件的检测机制到底是啥呢，我有点摸不清头脑了，是根据你上一次滑动的相似度来判断吗？

**Comment by McMug2020** [comment]
@dundunnp 作者您好，目前验证代码更新如下，测试通过几率较大

/**
 * 处理访问异常
 */
function handling_access_exceptions() {
    // 在子线程执行的定时器，如果不用子线程，则无法获取弹出页面的控件
    var thread_handling_access_exceptions = threads.start(function() {
        while (true) {
            textContains("访问异常").waitFor();
            // 滑动按钮“>>”位置
            idContains("nc_1_n1t").waitFor();
            var bound = idContains("nc_1_n1t").findOne().bounds();
            // 滑动边框位置
            text("向右滑动验证").waitFor();
            var slider_bound = text("向右滑动验证").findOne().bounds();
            // 通过更复杂的手势验证（向右滑动过程中途停顿）
            var x_start = bound.centerX();
            var dx = x_start - slider_bound.left;
            var x_end = slider_bound.right - dx;
            var x_mid = (x_end - x_start) * random(5, 9) / 10 + x_start;
            var y_start = random(bound.top, bound.bottom);
            var y_end = random(bound.top, bound.bottom);
            x_start = random(x_start - 7, x_start);
            x_end = random(x_end, x_end + 10);
            gesture(random(delay_time, delay_time + 50), [x_start, y_start], [x_mid, y_end], [x_end, y_end]);
            sleep(delay_time / 2);
            if (textContains("刷新").exists()) {
                click("刷新");
                continue;
            }
            if (textContains("网络开小差").exists()) {
                click("确定");
                continue;
            }
            // 执行脚本只需通过一次验证即可，防止占用资源
            break;
        }
    });
    return thread_handling_access_exceptions;
}

/* 
处理访问异常，滑动验证
*/
var thread_handling_access_exceptions = handling_access_exceptions();
