### ISSUE TITLE
无法自动滑块验证

### ISSUE THREAD

**Issue by asdfa324** [dundunnp/auto_xuexiqiangguo#463]

**Comment by songjiang951130** [comment]
我也出现这个问题了，麻烦作者看一下，感谢

**Comment by asdfa324** [comment]
> 我也出现这个问题了，麻烦作者看一下，感谢

我更新最新的代码就好了

**Comment by songjiang951130** [comment]
![image](https://user-images.githubusercontent.com/20123559/183230414-67042bcc-f232-40ae-b302-5df56658e088.png)
我更新了没有好，我感觉这个随机值不如去中点的值
