### ISSUE TITLE
20220819脚本的读文章功能好像无法使用了？

### ISSUE THREAD

**Issue by po1s0nnnn** [dundunnp/auto_xuexiqiangguo#475]
自动打开软件后停留在“亮点”一栏不动了，但刷完文章后再运行脚本，后面的自动刷视频和答题评论等功能是正常运行的

**Comment by songjiang951130** [comment]
> 自动打开软件后停留在“亮点”一栏不动了，但刷完文章后再运行脚本，后面的自动刷视频和答题评论等功能是正常运行的

`// 阅读文章次数
var count = 0;
var single_total_read = 63000
var titleSet = new Set();
while ((count < 6 - completed_read_count) && !finish_list[0]) {
    if (count == 0) {
        //点击菜单栏[要闻]
        className('android.view.ViewGroup').depth(15).findOnce(2).child(1).click();
        sleep(random_time(delay_time));
    }
    log("开始阅读：completed_read_count:{} count:{}", completed_read_count, count)
    swipe(800, 2000, 800, 600, 2000);
    sleep(random_time(delay_time));
    var articles = id("general_card_title_id").className("android.widget.TextView").find();
    log("找文章列表 length:", articles.length)

    if (articles.length == 0) {
        log("未找到文章，进行刷新");
        swipe(800, 2000, 800, 600, 2000);
        sleep(random_time(delay_time));
        continue;
    }

    for (var i = 0; i < articles.length; i++) {
        if (titleSet.has(articles[i].text())) {
            continue;
        }
        if (articles[i].text().includes("朗读") || articles[i].text().includes("朗诵") || articles[i].text().includes("专题")) {
            continue;
        }

        if (articles[i].parent() == null || articles[i].parent().parent() == null) {
            continue;
        }
        var cr = articles[i].parent().parent().click();
        if (!cr) {
            log("点击失败");
            continue;
        }
        sleep(random_time(delay_time));
        log("title: ", articles[i].text())

        var use_time = 0;
        while (!text('提醒').exists()) {
            //向下滑动
            swipe(500, 1700, 500, 700, 3000);
            use_time += 3000;
            if (use_time > 20000) {
                break;
            }
        }
        log("本次滑动时间：", use_time)
        sleep(Math.abs(single_total_read - use_time));
        log("阅读完成 article length", articles.length, " i:", i, "title:", articles[i].text());
        titleSet.add(articles[i].text());
        back();
        count++;
    }
}` 试试我这一段代码，我感觉是文章id变了，然后作者的专题回退也有问题

**Comment by po1s0nnnn** [comment]
> > 自动打开软件后停留在“亮点”一栏不动了，但刷完文章后再运行脚本，后面的自动刷视频和答题评论等功能是正常运行的
> 
> ```
> // 阅读文章次数
> var count = 0;
> var single_total_read = 63000
> var titleSet = new Set();
> while ((count < 6 - completed_read_count) && !finish_list[0]) {
>     if (count == 0) {
>         //点击菜单栏[要闻]
>         className('android.view.ViewGroup').depth(15).findOnce(2).child(1).click();
>         sleep(random_time(delay_time));
>     }
>     log("开始阅读：completed_read_count:{} count:{}", completed_read_count, count)
>     swipe(800, 2000, 800, 600, 2000);
>     sleep(random_time(delay_time));
>     var articles = id("general_card_title_id").className("android.widget.TextView").find();
>     log("找文章列表 length:", articles.length)
> 
>     if (articles.length == 0) {
>         log("未找到文章，进行刷新");
>         swipe(800, 2000, 800, 600, 2000);
>         sleep(random_time(delay_time));
>         continue;
>     }
> 
>     for (var i = 0; i < articles.length; i++) {
>         if (titleSet.has(articles[i].text())) {
>             continue;
>         }
>         if (articles[i].text().includes("朗读") || articles[i].text().includes("朗诵") || articles[i].text().includes("专题")) {
>             continue;
>         }
> 
>         if (articles[i].parent() == null || articles[i].parent().parent() == null) {
>             continue;
>         }
>         var cr = articles[i].parent().parent().click();
>         if (!cr) {
>             log("点击失败");
>             continue;
>         }
>         sleep(random_time(delay_time));
>         log("title: ", articles[i].text())
> 
>         var use_time = 0;
>         while (!text('提醒').exists()) {
>             //向下滑动
>             swipe(500, 1700, 500, 700, 3000);
>             use_time += 3000;
>             if (use_time > 20000) {
>                 break;
>             }
>         }
>         log("本次滑动时间：", use_time)
>         sleep(Math.abs(single_total_read - use_time));
>         log("阅读完成 article length", articles.length, " i:", i, "title:", articles[i].text());
>         titleSet.add(articles[i].text());
>         back();
>         count++;
>     }
> }
> ```
> 
> 试试我这一段代码，我感觉是文章id变了，然后作者的专题回退也有问题

感谢，替换之后试了一下，还是会卡在“亮点”一栏，然后自动结束，不知道是不是没替换好的原因

**Comment by McMug2020** [comment]
请问是什么版本的学习软件？
用2.33.0，并没有这个亮点的频道

**Comment by wccxp** [comment]
更新2.39增加了“亮点”一栏，把功能中的“3”改“4”就都正常了。

**Comment by po1s0nnnn** [comment]
> 

看了下应该是应用商店自动更新最新版了，回退到旧版就正常了

**Comment by po1s0nnnn** [comment]
> 请问是什么版本的学习软件？ 用2.33.0，并没有这个亮点的频道


看了下应该是应用商店自动更新最新版了，回退到旧版就正常了

**Comment by po1s0nnnn** [comment]
> 更新2.39增加了“亮点”一栏，把功能中的“3”改“4”就都正常了。

好像找不到有“3”的地方，请问具体是哪一条啊？

**Comment by lf9421** [comment]
大家都遇到了这个问题，其实就是因为新增了一个亮点模块，导致无法继续，有没有哪位懂代码的，调试调试

**Comment by lf9421** [comment]
> 更新2.39增加了“亮点”一栏，把功能中的“3”改“4”就都正常了。

对，就是因为了“亮点”一栏，但你说的功能，在哪改？

**Comment by raawaa** [comment]
> > 更新2.39增加了“亮点”一栏，把功能中的“3”改“4”就都正常了。
> 
> 对，就是因为了“亮点”一栏，但你说的功能，在哪改？


把这里的3改成4试试看：
https://github.com/dundunnp/auto_xuexiqiangguo/blob/d352c26c8f6157212036aa023e23c300150c39ea/Hamibot/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js#L409

**Comment by lf9421** [comment]
大家都遇到了这个问题，其实就是因为新增了一个亮点模块，导致无法继续，有没有哪位懂代码的，调试调试

**Comment by lf9421** [comment]
> > > 更新2.39增加了“亮点”一栏，把功能中的“3”改“4”就都正常了。
> > 
> > 对，就是因为了“亮点”一栏，但你说的功能，在哪改？
> 
> 
> 把这里的3改成4试试看：
> https://github.com/dundunnp/auto_xuexiqiangguo/blob/d352c26c8f6157212036aa023e23c300150c39ea/Hamibot/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js#L409

大哥，你能说具体点吗？哪行代码？还是怎么改，你说个3改4怎么改啊

**Comment by lf9421** [comment]
怎么关闭了？你调试好了？
