### ISSUE TITLE
hamibot中new学习强国.js卡在学习积分页面

### ISSUE THREAD

**Issue by blw1992** [dundunnp/auto_xuexiqiangguo#494]
![9fda6197ca0058035c6b262f70514da](https://user-images.githubusercontent.com/95850431/189051061-7a8cc0fb-168d-4e96-99e8-33eb68194dbd.jpg)
日志截图

**Comment by dundunnp** [comment]
额，有没有可能你的界面并不是新界面

**Comment by McMug2020** [comment]
> 额，有没有可能你的界面并不是新界面

学习积分 这几个字下移了一层，目前代码获取不到。

**Comment by klcb2010** [comment]
new和非new都会卡在学习积分界面，非new 把className("android.view.ViewGroup").depth(15).findOnce(2).child(3).click(); 3改成4学满16分就结束 然后卡在学习积分界面，new直接卡在学习积分界面

**Comment by blw1992** [comment]
> 额，有没有可能你的界面并不是新界面

今天再次运行，会跳转到学习积分商城

**Comment by yanzhang4013** [comment]
同样卡强国城（积分商城）安卓12   使用new  强国已经是2.33
