### ISSUE TITLE
卡在积分界面

### ISSUE THREAD

**Issue by Asereint** [dundunnp/auto_xuexiqiangguo#502]
用了新版本还是卡在积分界面

**Comment by klcb2010** [comment]
说一下你的运行环境  如果是机器人  导入https://github.com/dundunnp/auto_xuexiqiangguo/tree/version-15.6/Hamibot

**Comment by dundunnp** [comment]
请问你的界面是新界面嘛
<div align=center>
<img src="https://user-images.githubusercontent.com/68000706/189031879-c9844e66-2ac5-41b0-ab3b-b4a39a7c5ec1.jpg" alt="msedge_WRzp0mov3N" width="200px" style="zoom:33%;" />
</div>

**Comment by Asereint** [comment]
> 请问你的界面是新界面嘛
> 
> <img alt="msedge_WRzp0mov3N" width="200px" src="https://user-images.githubusercontent.com/68000706/189031879-c9844e66-2ac5-41b0-ab3b-b4a39a7c5ec1.jpg">

对啊
