### ISSUE TITLE
夜神模拟器无法使用

### ISSUE THREAD

**Issue by 736473283** [dundunnp/auto_xuexiqiangguo#53]
配置完成后，脚本可以启动app，但是点击积分页后过几秒，报错如图，然后控制台显示bot停止运行
![image](https://user-images.githubusercontent.com/24606375/145205524-3608098b-30f5-4e2c-9cfd-ecf381b6e397.png)

**Comment by howpic** [comment]
同样问题，雷电模拟器

**Comment by Windows55** [comment]
逍遥模拟器也无法使用，提示：
[](url)[
![微信图片_20211210164838](https://user-images.githubusercontent.com/95908437/145545032-81b20290-e21e-450f-8b8b-e811214b64c9.jpg)
](url)

**Comment by 736473283** [comment]
可参考我的新提出issue#265
