### ISSUE TITLE
错误无法启动，提示150行错误（未改变代码行数），请教是怎么回事

### ISSUE THREAD

**Issue by changsin2000** [dundunnp/auto_xuexiqiangguo#531]
使用的Auto.js Pro，华为p40pro手机，9月之前的版本还可以正常运行，现在15.6版的最新脚本，新版本无法运行了。配置信息方面仅配置了AK和SK。
150行的代码为：answer_question_bank = JSON.parse(answer_question_bank);
错误信息如下：
![error](https://user-images.githubusercontent.com/54618733/189924336-bb6a5ff9-45b9-4d6f-bebf-ae5f905aa9cd.jpg)

**Comment by Adufun** [comment]
第143行，换个加速链地址，地址可参考https://github.com/fhefh2015/Fast-GitHub/issues/44
![YSPRMIYBV4QP3G 0RFHZ7HK](https://user-images.githubusercontent.com/61834743/190548539-302f6fb6-9aae-4d99-95d7-73281f26780c.png)
