### ISSUE TITLE
运行脚本卡在积分商城

### ISSUE THREAD

**Issue by blw1992** [dundunnp/auto_xuexiqiangguo#532]
如题，运行new脚本后会打开两次学习积分页面，然后会跳转到强国积分商城就卡住了，hamibot日志显示“等待: my_back”
![480ce214d9ff8ec35335020165a7090](https://user-images.githubusercontent.com/95850431/190052081-565a0ed0-db6d-4a8c-b20b-acda824d5dfa.jpg)
![e9579d6a6928d7f9e0a560da83ff2dc](https://user-images.githubusercontent.com/95850431/190052096-ec95da88-5058-43b6-882c-f31961c78071.jpg)

**Comment by mapleshadow** [comment]
确实是这样，会卡住，或者卡强国商城

**Comment by dundunnp** [comment]
看日志信息貌似控件没有读取到，但你的界面是新界面，意味着新界面有几套版本（?）因为我没有太多设备，我也不好调试啊

**Comment by blw1992** [comment]
> 看日志信息貌似控件没有读取到，但你的界面是新界面，意味着新界面有几套版本（?）因为我没有太多设备，我也不好调试啊

是不是因为安卓版本的问题，我在用的是安卓13，我尝试用安卓9的机器运行脚本没有问题

**Comment by mapleshadow** [comment]
> > 看日志信息貌似控件没有读取到，但你的界面是新界面，意味着新界面有几套版本（?）因为我没有太多设备，我也不好调试啊
> 
> 是不是因为安卓版本的问题，我在用的是安卓13，我尝试用安卓9的机器运行脚本没有问题

我也是13，难道真是android版本问题？不同的版本，用的sdk不同？
