### ISSUE TITLE
如何多开/切换账号

### ISSUE THREAD

**Issue by choudewanmei** [dundunnp/auto_xuexiqiangguo#540]
作者你好，我想请教一下，如何实现多开/切换账号呢？

因为我跟女友俩人都要刷，现在我的解决方案是双开强国app，然后运行两次脚本，不能同时运行，所以，我想请教一下，如何在一台设备上实现双开/切换账号的功能，感谢作者大大！

**Comment by AnonyEastRainbow** [comment]
你是懒到了切个账号的时间都没有吗

**Comment by xiangshang-kok** [comment]
小米手机，应用双开

**Comment by choudewanmei** [comment]
> 小米手机，应用双开

我现在的方案就是双开了，然后跑两次。我的意思是，脚本能不能在app里实现切换账号，一次跑两个账号。

**Comment by zhufscug** [comment]
作者不会这么做，这个需求太小众了，没有必要为小众的需求去做，大部分人都是一个账号
