### ISSUE TITLE
本地题库储存目录在哪里，网盘挂掉了

### ISSUE THREAD

**Issue by DeerXX** [dundunnp/auto_xuexiqiangguo#544]
### 
![21c32d43800705781bd520839300d70](https://user-images.githubusercontent.com/114485151/192567441-99c813fb-d2e0-413a-9427-413454d8d946.jpg)

**Comment by BigFireDog** [comment]
同遇到这个问题，不知道是什么原因

**Comment by DeerXX** [comment]
已找到问题，是题库链接坏了，更换一下题库链接就好了

**Comment by BigFireDog** [comment]
是修改腾讯云的那个链接吗？前面的github的链接是能够访问的

**Comment by DeerXX** [comment]
好的
