### ISSUE TITLE
卡在各种无意义操作不继续执行脚本，求助

### ISSUE THREAD

**Issue by YoYspoon** [dundunnp/auto_xuexiqiangguo#597]
手机华为荣耀型号忘了，用的hamibot，前段时间使用正常，最近一星期每天都会在不一定具体那个页面卡住，有时是听广播界面不会选中广播，有时是地方新闻一直刷新，有时候是双人对战不停尝试退出对战，也有过不停返回订阅界面之类，总之是要么不停重复无意义操作，要么在一个地方卡住不进行任何操作，确认了脚本版本是15.72，app版本2.33

**Comment by dundunnp** [comment]
看看日志是不是经常断开连接呢，系统是啥

**Comment by YoYspoon** [comment]
系统就是荣耀原生的忘了版本号了，日志里没有任何报错或者断开连接之类，就是单纯的：执行xxx，然后就没有下文了

后来改用hamibot脚本市场里的autoxuexi+脚本（不知道是不是你做的）和改版本号版app每天可以成功运行一次，第二天开始验证不出滑动条会卡住，又用回普通版2.33app和autoxuexi+可以完美运行了。
