### ISSUE TITLE
无法选择正确选项

### ISSUE THREAD

**Issue by dsus4wang** [dundunnp/auto_xuexiqiangguo#6]
您好，请问现在题库还是不能用吗？2021年12月2日11:35:07答题的时候，还是只选择第一项，华为云OCR是调用成功的

**Comment by dundunnp** [comment]
可以，我用自己手机正确率有80以上，可能原因是网络原因或手机性能没有读取到题目，你可以试试增大配置选项里的延迟时间，另外我会考虑在新版本中增大加载时间
