### ISSUE TITLE
鸿蒙3.0，报错

### ISSUE THREAD

**Issue by peizhennan** [dundunnp/auto_xuexiqiangguo#603]
鸿蒙3.0，报错，最新版本
![Screenshot_20230101_101044_com hamibot hamibot](https://user-images.githubusercontent.com/71214374/210159227-074b84c8-4f88-454f-b01f-3a25cebaa435.jpg)

**Comment by dundunnp** [comment]
怎么就鸿蒙3了啊。。。我的旧手机还是2，看样子是系统的问题，某个控件没获取到，但我也调试不了啊

**Comment by peizhennan** [comment]
感谢回复！！
