### ISSUE TITLE
希望作者大大能新增第三方OCR

### ISSUE THREAD

**Issue by qa1511** [dundunnp/auto_xuexiqiangguo#616]
百度云OCR中的通用文字识别（标准版）显示带开通付费了
![image](https://user-images.githubusercontent.com/68044932/211234119-44812d15-2fbd-4e7c-8735-ea948a230bf5.png)
，希望作者大大能新增免费的第三方OCR

**Comment by qa1511** [comment]
![image](https://user-images.githubusercontent.com/68044932/211234165-179a6f86-d008-4943-a5a2-d2ebd6fab07e.png)

**Comment by dundunnp** [comment]
我看了下，只是需要多一步开通操作吧，调用量限制还是有1000次/月赠送的

**Comment by qa1511** [comment]
> 

请问是开通按量后付费吗，点击开通以后他会显示这个
![image](https://user-images.githubusercontent.com/68044932/211247800-e2337a1c-1bea-479d-baf0-be8a229f7497.png)
，我不知道他这样是不是要收费呀，看上面是0.005元／次？

**Comment by qa1511** [comment]
> 我看了下，只是需要多一步开通操作吧，调用量限制还是有1000次/月赠送的
请问是开通按量后付费吗，点击开通以后他会显示这个
![image](https://user-images.githubusercontent.com/68044932/211248019-bd38deb0-27d3-4b8c-a1fc-8f47ce05ab77.png)
，我不知道他这样是不是要收费呀，看上面是0.005元／次？

**Comment by dundunnp** [comment]
是的，注意是 通用文字识别（标准含位置版）

**Comment by qa1511** [comment]
> 是的，注意是 通用文字识别（标准含位置版）

收到，感谢作者
