### ISSUE TITLE
安卓13 用虚拟机完全可以解决问题

### ISSUE THREAD

**Issue by Jay32321** [dundunnp/auto_xuexiqiangguo#626]
最近才知道有个vm什么的虚拟机 可以完美解决13的问题 百度上面有破解版 一用是真的神奇

**Comment by wu12000** [comment]
虚拟机叫什么?

**Comment by xiaoxutem** [comment]
> 最近才知道有个vm什么的虚拟机 可以完美解决13的问题 百度上面有破解版 一用是真的神奇

VMOS 虚拟机7.1 64位测试成功，多开虚拟机还可以挂多个账号，之前一直用旧手机来挂，现在终于不用那么麻烦了，感谢

**Comment by dundunnp** [comment]
大家注意，这三个刚创建的账号看上去像托。我自己也试了一下这个软件，需要付费，请大家谨慎，后续我也会找一些免费方便的方法解决这个问题
