### ISSUE TITLE
Hamibot脚本的运行按钮是灰色的，无法点击运行

### ISSUE THREAD

**Issue by robinvicky** [dundunnp/auto_xuexiqiangguo#688]
如下图：Hamibot脚本的运行按钮是灰色的，无法点击运行，是什么原因啊？
![image](https://user-images.githubusercontent.com/75261272/224865416-9f66f022-ec1c-4582-9c25-1345f6d16af0.png)

**Comment by Fizzyi** [comment]
这个一般是你的机器没有上线
